spring.application.name=projetotea-auth

spring.datasource.url=jdbc:mysql://localhost:3306/projetotea?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.web.error.include-stacktrace=never

projetotea.jwt.keystore.path=keystores/projetotea.jks
projetotea.jwt.keystore.password=${KEYSTORE_PASSWORD}
projetotea.jwt.keystore.keypair-alias=algafood

spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.deserialization.fail-on-ignored-properties=true

server.port=8081
